### ISSUE TITLE
Error message goes beyond screen borders (Mensaje de error cortado al introducir contraseña de archivo errónea)

### ISSUE THREAD

**Issue by vilcholo** [npalumbo/keepassui#15]
Cuando accedes a Load Keepass file e introduces una contraseña incorrecta se muestra el mensaje de error cortado.

![IMG-20240201-WA0001](https://github.com/npalumbo/keepassui/assets/158450364/995d2f17-70eb-4d31-9e31-6c144782cf12)

**Comment by npalumbo** [comment]
> Cuando accedes a Load Keepass file e introduces una contraseña incorrecta se muestra el mensaje de error cortado.
> 
> ![IMG-20240201-WA0001](https://private-user-images.githubusercontent.com/158450364/301440525-995d2f17-70eb-4d31-9e31-6c144782cf12.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3OTkzMzYsIm5iZiI6MTcwNjc5OTAzNiwicGF0aCI6Ii8xNTg0NTAzNjQvMzAxNDQwNTI1LTk5NWQyZjE3LTcwZWItNGQzMS05ZTMxLTZjMTQ0NzgyY2YxMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxNDUwMzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDBiOGFhNmIzY2M1ZGE0N2U0NDM2Y2YwZWNkNjEzZTRlNWY2MjlhMzJhYjdjNDFkNTg3MzY1NTg2YjgwOGRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DbGSAvEtk2ZBN5IuvrB64GRH1kfGoyot726yYadPu7c)

English Translation:
When you enter an incorrect master password. The message dialog shows text that goes beyond screen borders.

**Comment by npalumbo** [comment]
This is linked to the following bug of the fyne library which is aimed to be fixed in early 2024 :
https://github.com/fyne-io/fyne/issues/2602.
Tagged the issue with the "depends-on-fyne-bugfix" label.

Spanish: Esto esta relacionado con el siguiente bug de fyne que esta programado para ser solucionado a comienzos de 2024: https://github.com/fyne-io/fyne/issues/2602.

**Comment by npalumbo** [comment]
This was fixed by upgrading the fyne version here, that went live on release 34: https://github.com/npalumbo/keepassui/issues/46
![fixed_text_wrapping](https://github.com/user-attachments/assets/c307d124-e930-43c9-bbb9-89de8e5de6a8)
