### ISSUE TITLE
Enter master passwords dialog shows a previously entered password (Formulario Enter master password muestra última password introducida)

### ISSUE THREAD

**Issue by vilcholo** [npalumbo/keepassui#16]
Pasos para reproducir:

1. Entrar en Load Keepass file
2. Seleccionar un fichero
3. Introducir la contraseña (ya sea correcta o incorrecta)
4. Confirmar
5. Volver a entrar en Load Keepass file
6. Seleccionar fichero
7. En formulario Enter master password muestra la última contraseña introducida

![Screenshot_2024-02-01-09-39-03-070_com keepassui](https://github.com/npalumbo/keepassui/assets/158450364/d2f4cc7a-7bbc-4623-a8ef-6e532b4d67f3)

**Comment by npalumbo** [comment]
> Pasos para reproducir:
> 
> 1. Entrar en Load Keepass file
> 2. Seleccionar un fichero
> 3. Introducir la contraseña (ya sea correcta o incorrecta)
> 4. Confirmar
> 5. Volver a entrar en Load Keepass file
> 6. Seleccionar fichero
> 7. En formulario Enter master password muestra la última contraseña introducida
> 
> ![Screenshot_2024-02-01-09-39-03-070_com keepassui](https://private-user-images.githubusercontent.com/158450364/301443206-d2f4cc7a-7bbc-4623-a8ef-6e532b4d67f3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3ODcwMzAsIm5iZiI6MTcwNjc4NjczMCwicGF0aCI6Ii8xNTg0NTAzNjQvMzAxNDQzMjA2LWQyZjRjYzdhLTdiYmMtNDYyMy1hOGVmLTZlNTMyYjRkNjdmMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQxMTI1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGU1NzQ1NjVmYWVmODYxMGNiZGY2MmIwNGFmOGVjMjdmYTAwMDJjMDYxY2I1NDRiYjlhZjM4YTJiNjVmMDM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1WzayZyxiHK4IZ5gH7NSFc34glpuX4BAMO8PLXE4vKM)

English Translation:
1. Tap on the Load Keepass file button
2. Select a file
3. Enter a master password (doesn't matter if it is correct)
4. Tap on Confirm
5. Tap on the Load Keepass file button
6. Select a file
7. The Enter master password dialog shows a previously entered password
