### ISSUE TITLE
App crashes when opening a second file (Al abrir un segundo fichero se cierra de manera inesperada)

### ISSUE THREAD

**Issue by vilcholo** [npalumbo/keepassui#17]
Pasos para reproducir:

1. Entrar en Load Keepass file
2. Seleccionar un fichero
3. Introducir la contraseña (contraseña correcta)
4. Confirmar
5. Volver a entrar en Load Keepass file
6. Seleccionar fichero
7. Introducir la contraseña (contraseña correcta)
8. Confirmar
9. La aplicación se cierra de manera inesperada

**Comment by npalumbo** [comment]
> Pasos para reproducir:
> 
> 1. Entrar en Load Keepass file
> 2. Seleccionar un fichero
> 3. Introducir la contraseña (contraseña correcta)
> 4. Confirmar
> 5. Volver a entrar en Load Keepass file
> 6. Seleccionar fichero
> 7. Introducir la contraseña (contraseña correcta)
> 8. Confirmar
> 9. La aplicación se cierra de manera inesperada

1. Tap on the Load Keepass file button
2. Select a file
3. Enter a correct master password
4. Tap on Confirm
5. Tap again on the  Load Keepass file button
6. Select a file
7. Enter a correct master password
8. Confirm
9. The app crashes
