### ISSUE TITLE
Allow to lock files (Opción para cerrar fichero)

### ISSUE THREAD

**Issue by vilcholo** [npalumbo/keepassui#18]
Se propone opción para cerrar el fichero abierto actualmente.
Para cerrar el fichero hay que cerrar la app completamente y volver a ejecutarla.

**Comment by npalumbo** [comment]
> Se propone opción para cerrar el fichero abierto actualmente. Para cerrar el fichero hay que cerrar la app completamente y volver a ejecutarla.

English translation: Allow to lock the current keepass file opened. In order to lock the file we currently need to completely close the app.
